language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - oraclejdk11
  - openjdk8
  - openjdk-ea
os:
  - linux
#  - osx
#before_script:
#  - npm install
#cache:
#  directories:
#    - "node_modules"


#  mvn test -B
